import { useState } from 'react';
import { Download, Package, FileText, Code2, BookOpen, Settings } from 'lucide-react';

const EXT = { javascript: 'js', python: 'py', java: 'java' };

function generateReadme(apiData, language) {
  const name = apiData?.baseUrl?.replace(/https?:\/\//, '').split('/')[0] || 'API';
  return `# ${name} SDK

Auto-generated by Doc2SDK — AI-Powered API Integration Copilot

## Overview
Base URL: ${apiData?.baseUrl || 'Not specified'}
Authentication: ${apiData?.authentication || 'Not specified'}
Endpoints: ${(apiData?.endpoints || []).length}

## Installation
${language === 'javascript' ? 'npm install\nnode example.js' :
  language === 'python'     ? 'pip install -r requirements.txt\npython example.py' :
                              'mvn install\njava -jar app.jar'}

## Quick Start
See \`example.${EXT[language] || 'txt'}\` for usage examples.

## Endpoints
${(apiData?.endpoints || []).map(e => `- ${e.method || 'GET'} ${e.path || '/'} — ${e.description || ''}`).join('\n')}

---
Generated by Doc2SDK · https://github.com/doc2sdk
`;
}

function generateConfig(apiData, language) {
  const baseUrl = apiData?.baseUrl || 'https://api.example.com';
  if (language === 'javascript') {
    return `// config.js — Doc2SDK Generated
module.exports = {
  BASE_URL: '${baseUrl}',
  TIMEOUT: 10000,
  RETRY_ATTEMPTS: 3,
  API_KEY: process.env.API_KEY || '',
};
`;
  }
  if (language === 'python') {
    return `# config.py — Doc2SDK Generated
import os

BASE_URL = '${baseUrl}'
TIMEOUT = 10
RETRY_ATTEMPTS = 3
API_KEY = os.getenv('API_KEY', '')
`;
  }
  return `// config.java — Doc2SDK Generated
public class Config {
    public static final String BASE_URL = "${baseUrl}";
    public static final int TIMEOUT = 10000;
    public static final String API_KEY = System.getenv("API_KEY");
}
`;
}

function generateDepsFile(language) {
  if (language === 'javascript') return `{\n  "dependencies": {\n    "axios": "^1.6.0"\n  }\n}\n`;
  if (language === 'python')     return `requests>=2.31.0\nurllib3>=2.0.0\n`;
  return `<dependencies>\n  <dependency>\n    <groupId>com.squareup.okhttp3</groupId>\n    <artifactId>okhttp</artifactId>\n    <version>4.12.0</version>\n  </dependency>\n</dependencies>\n`;
}

export default function ZipDownload({ apiData, generationData, language = 'javascript' }) {
  const [downloading, setDownloading] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      // Dynamic import of jszip
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();

      const ext = EXT[language] || 'js';
      const folder = zip.folder('sdk-project');

      folder.file('README.md',                generateReadme(apiData, language));
      folder.file(`config.${ext}`,            generateConfig(apiData, language));
      folder.file(`client.${ext}`,            generationData?.wrapperCode || '// Generated wrapper code');
      folder.file(`example.${ext}`,           `// Example usage\n// Import the client and call your endpoints\n`);
      folder.file(
        language === 'python' ? 'requirements.txt' : language === 'java' ? 'pom.xml' : 'package.json',
        generateDepsFile(language)
      );
      folder.file('.env.example',             `API_KEY=your_api_key_here\nBASE_URL=${apiData?.baseUrl || ''}\n`);
      folder.file('SETUP.md',                 `# Setup\n\n${generationData?.integrationGuide || 'See README.md for setup instructions.'}\n`);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href     = url;
      a.download = 'SDKProject.zip';
      a.click();
      URL.revokeObjectURL(url);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (err) {
      console.error('ZIP generation failed:', err);
      alert('ZIP generation failed. Make sure jszip is installed: npm install jszip');
    } finally {
      setDownloading(false);
    }
  };

  const files = [
    { icon: <FileText size={13} />,  name: 'README.md',                  desc: 'Project overview and quick start' },
    { icon: <Settings size={13} />,  name: `config.${EXT[language]||'js'}`, desc: 'Base URL, timeout, auth config' },
    { icon: <Code2 size={13} />,     name: `client.${EXT[language]||'js'}`, desc: 'Auto-generated API wrapper class' },
    { icon: <Code2 size={13} />,     name: `example.${EXT[language]||'js'}`,desc: 'Usage examples with all endpoints' },
    { icon: <Package size={13} />,   name: language === 'python' ? 'requirements.txt' : language === 'java' ? 'pom.xml' : 'package.json', desc: 'Dependencies file' },
    { icon: <FileText size={13} />,  name: '.env.example',               desc: 'Environment variable template' },
    { icon: <BookOpen size={13} />,  name: 'SETUP.md',                   desc: 'Step-by-step integration guide' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

      {/* Header card */}
      <div className="card" style={{ padding: '1.25rem' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', flexWrap: 'wrap' }}>
          <div>
            <p style={{ fontSize: '0.7rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#666660', marginBottom: '0.35rem' }}>
              Complete Project Download
            </p>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#ede5d0', marginBottom: '0.4rem' }}>
              SDKProject.zip
            </h2>
            <p style={{ fontSize: '0.78rem', color: '#8a8a80', lineHeight: 1.6, maxWidth: '480px' }}>
              Download a complete, ready-to-use SDK project folder containing all configuration, 
              wrapper code, dependencies, and documentation — drop it into your project and start integrating.
            </p>
          </div>
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="btn-primary"
            style={{ padding: '0.65rem 1.5rem', fontSize: '0.75rem', flexShrink: 0 }}
          >
            {downloading ? (
              <>
                <svg className="animate-spin" width="14" height="14" viewBox="0 0 24 24" fill="none">
                  <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" opacity="0.25"/>
                  <path fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" opacity="0.75"/>
                </svg>
                Packing...
              </>
            ) : done ? (
              <>✓ Downloaded</>
            ) : (
              <><Download size={14} /> Download ZIP</>
            )}
          </button>
        </div>
      </div>

      {/* File manifest */}
      <div className="card" style={{ overflow: 'hidden' }}>
        <div style={{ padding: '0.75rem 1rem', borderBottom: '1px solid #1a2e22' }}>
          <span style={{ fontSize: '0.7rem', fontWeight: 600, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#b0a898' }}>
            Package Contents — {files.length} files
          </span>
        </div>
        <div>
          {files.map((f, i) => (
            <div key={i} style={{
              display: 'flex', alignItems: 'center', gap: '0.75rem',
              padding: '0.7rem 1rem',
              borderBottom: i < files.length - 1 ? '1px solid #1a2e22' : 'none',
            }}>
              <span style={{ color: '#c9a84c' }}>{f.icon}</span>
              <code style={{ fontSize: '0.75rem', fontFamily: 'JetBrains Mono, monospace', color: '#ede5d0', minWidth: '180px' }}>
                {f.name}
              </code>
              <span style={{ fontSize: '0.72rem', color: '#666660' }}>{f.desc}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Note */}
      <p style={{ fontSize: '0.7rem', color: '#666660', lineHeight: 1.7, paddingLeft: '0.25rem' }}>
        All files are generated from your API analysis. The wrapper code is production-ready with authentication, error handling, and typed method signatures for every detected endpoint.
      </p>
    </div>
  );
}
